### ISSUE TITLE
Update to a supported OS

### ISSUE THREAD

**Issue by ZNackasha** [phusion/holy-build-box#10] opened 2018-09-20 17:46 UTC
As you may be aware CentOS 5 is no longer supported. I was wondering if its possible to update to a supported OS?

**Comment by culpinnis** [comment] 2018-10-19 13:33
I ran in this issue, too. I was trying to install some dependencies with yum, but the repository index is no longer available on the centos servers. 

`Enabling base-source repository
http://vault.centos.org/centos/5/os/Source/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found`

**Comment by 4O4** [comment] 2018-10-21 14:27
@culpinnis What package are you trying to install? I've just tested it and seems to work fine. Here's my `/etc/yum.repos.d/CentOS-Base.repo`:

```
# CentOS-Base.repo
#
# The mirror system uses the connecting IP address of the client and the
# update status of each mirror to pick mirrors that are updated to and
# geographically close to the client.  You should use this for CentOS updates
# unless you are manually picking other mirrors.
#
# If the mirrorlist= does not work for you, as a fall back you can try the
# remarked out baseurl= line instead.
#
#

[base]
name=CentOS-$releasever - Base
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
baseurl=http://vault.centos.org/5.11/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

#released updates
[updates]
name=CentOS-$releasever - Updates
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates
baseurl=http://vault.centos.org/5.11/updates/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras
baseurl=http://vault.centos.org/5.11/extras/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

#additional packages that extend functionality of existing packages
[centosplus]
name=CentOS-$releasever - Plus
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus
baseurl=http://vault.centos.org/5.11/centosplus/$basearch/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5

#contrib - packages by Centos Users
[contrib]
name=CentOS-$releasever - Contrib
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=contrib
baseurl=http://vault.centos.org/5.11/contrib/$basearch/
gpgcheck=1
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-5
```

**Comment by culpinnis** [comment] 2018-10-22 09:51
Thanks for your reply. I tried to install the build-deps for R. 
But in fact the URL which was generated on my system is wrong. It should be 5.XX instead of plain 5.
I try to change the configuration before installing the dependencies.

Best wishes
Chris

**Comment by 4O4** [comment] 2018-10-22 15:40
Is it possible that you somehow have an outdated image pulled from the docker registry? Here's a line from the build script responsible for fixing up the URLs, it's been there for a while already:

https://github.com/phusion/holy-build-box/blob/master/image/build.sh#L72

**Comment by culpinnis** [comment] 2018-10-22 17:05
Ahhh thanks a lot! My dockerfile included version 1.2.2, changed it to the recent version.

**Comment by culpinnis** [comment] 2018-11-13 18:34
Hi, finally to execute` sed -i.bak -re 's/^(mirrorlist)/#\1/g' -e 's/^#(baseurl)/\1/g' -e 's/mirror(\.centos)/vault\1/g' -e 's|centos/\$releasever/([^/]+)/([^/]+)|5.11/\1/\2|g' /etc/yum.repos.d/CentOS-Sources.repo`
fixed my issue.

**Comment by FooBarWidget** [comment] 2021-01-08 13:15
Closing this issue because it's a duplicate of #23.

**Closed by FooBarWidget** 2021-01-08 13:15 UTC
